/**
 * Generates CREDITS.md from the licence metadata Sketchfab embeds in each glTF.
 *
 *   node scripts/credits.mjs
 *
 * Most of these models are CC-BY, which requires visible attribution wherever
 * the work is published. Reading it from the files rather than keeping a list
 * by hand means the credits cannot drift out of sync with what actually ships.
 */
import { NodeIO } from '@gltf-transform/core'
import { ALL_EXTENSIONS } from '@gltf-transform/extensions'
import draco3d from 'draco3dgltf'
import { readdirSync, writeFileSync } from 'node:fs'
import { join } from 'node:path'

/**
 * Reads the *shipped* models, not the source folder.
 *
 * The sources come and go as models are swapped, and crediting from them means
 * the file silently under-credits the moment one is removed — while the
 * optimised GLB is still on the site. gltf-transform carries asset.extras
 * through the pipeline, so what ships knows its own provenance.
 */
const OUT = 'public/models'

/**
 * Models whose files carry no embedded metadata — typically ones exported by
 * hand rather than downloaded straight from Sketchfab. Fill these in.
 */
const MANUAL = {
  // 'chair.glb': { title: '', author: '', license: '', source: '' },
}

const io = new NodeIO().registerExtensions(ALL_EXTENSIONS).registerDependencies({
  'draco3d.decoder': await draco3d.createDecoderModule(),
  'draco3d.encoder': await draco3d.createEncoderModule(),
})

const rows = []
const unknown = []
for (const file of readdirSync(OUT).filter((f) => f.endsWith('.glb'))) {
  const doc = await io.read(join(OUT, file))
  const e = { ...(doc.getRoot().getAsset().extras ?? {}), ...(MANUAL[file] ?? {}) }
  if (!e.title && !e.author) unknown.push(file)
  rows.push({
    file,
    title: e.title ?? file.replace(/\.glb$/, ''),
    author: e.author ?? 'unknown — verify before publishing',
    license: e.license ?? 'UNKNOWN — verify before publishing',
    source: e.source ?? '',
  })
}

rows.sort((a, b) => a.title.localeCompare(b.title))

const needsAttribution = rows.filter((r) => /CC-BY|CC BY/i.test(r.license))

const md = `# Credits

3D models used in the signature scene. Generated by \`scripts/credits.mjs\` —
do not edit by hand.

${
  needsAttribution.length
    ? `> **${needsAttribution.length} of these are CC-BY and require visible attribution**
> wherever the site is published. The About panel links here; keep that link.
`
    : ''
}
${rows
  .map((r) => {
    const name = r.source ? `[${r.title}](${r.source})` : r.title
    return `### ${name}\n- **Author:** ${r.author}\n- **License:** ${r.license}\n- **File:** \`${r.file}\`\n`
  })
  .join('\n')}
## Everything else

The desk, the VHS tapes and the wood grain are built in code — see
\`src/three/props/Desk.tsx\`, \`VhsShelf.tsx\` and \`src/hooks/useWoodTexture.ts\`.
`

writeFileSync('CREDITS.md', md)
console.log(`wrote CREDITS.md — ${rows.length} models, ${needsAttribution.length} need attribution`)
for (const r of rows) console.log(`  ${r.title.padEnd(34)} ${r.license.split(' ')[0]}`)

const nc = rows.filter((r) => /CC-BY-NC/i.test(r.license))
if (nc.length) {
  console.log(`\n!! ${nc.length} NON-COMMERCIAL model(s) — not licensed for commercial use:`)
  for (const r of nc) console.log(`   ${r.title} (${r.file})`)
}
if (unknown.length) {
  console.log(`\n!! no embedded licence in: ${unknown.join(', ')}`)
  console.log('   Add them to MANUAL in scripts/credits.mjs before publishing.')
}
